services:
  web:
    build: .
    container_name: school_dashboard_web
    ports:
      - "8080:1325"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - db


  db:
    image: postgres:15
    container_name: school_dashboard_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dat224551
      - POSTGRES_DB=school_dashboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: